const LOAD_COMMENTS = 'LOAD_COMMENTS'
const LOAD_POSTS = 'LOAD_POSTS'
const LOAD_USERS = 'LOAD_USERS'
const LOAD_SINGLE_USER = 'LOAD_SINGLE_USER'
const LOAD_SINGLE_POST = 'LOAD_SINGLE_POST'
const LOAD_SINGLE_COMMENTS = 'LOAD_SINGLE_COMMENTS'

export {
    LOAD_COMMENTS,
    LOAD_POSTS,
    LOAD_USERS,
    LOAD_SINGLE_USER,
    LOAD_SINGLE_POST,
    LOAD_SINGLE_COMMENTS
}